# Generated by Django 5.2.1 on 2025-08-18 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_city_is_active_city_is_featured_country_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='backendApp.guideprofile'),
        ),
    ]
