# Generated by Django 5.2.1 on 2025-08-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_package_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiderequestmodel',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='driving_license_photos/'),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='fb_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='nid',
            field=models.ImageField(blank=True, null=True, upload_to='nid_photos/'),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AlterField(
            model_name='guiderequestmodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guiderequestmodel',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
