# Generated by Django 5.2.1 on 2025-08-18 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_guiderequestmodel_driving_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='backendApp.guideprofile'),
        ),
    ]
